FROM node:6.6 
RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app
WORKDIR $HOME
COPY ./ ./
RUN npm install -g angular-cli@1.0.0-beta.28.3 
RUN npm cache clean
CMD my-project
CMD ng serve --host 0.0.0.0 --port 4000
EXPOSE 4000